image:
  repository: "vehiclesdashboardregistry.azurecr.io/customermanager"
  tag: "52"
  pullPolicy: "IfNotPresent"

replicas: 1

resources:
  requests:
    memory: 250Mi
    cpu: 40m
  limits:
    memory: 2Gi
    cpu: 1

env: {}
#  - name: "JAVA_OPTS2"
#    value: "-Dserver.port=8080"


service:
  name: customermanager.svc.cluster.local
  type: ClusterIP
  internalPort: 80
  externalPort:  8080
  ## Service annotations
  ##
  annotations: {}

ingress:
  ## If true, Application Ingress will be created
  ##
  enabled: false
  hosts: 
     - /
#    - /hello-world
#    - foo.example.com/hello-world

  ## Ingress annotations
  ##
  annotations: 
    kubernetes.io/ingress.class: traefik
    traefik.frontend.rule.type: PathPrefixStrip
