server:
  port: 8081
zuul:
   routes:
      getCustomers:
         path: /customers/v1/**
         url: http://customermanager.backend.svc.cluster.local:8082/customers
      getVehicles:
         path: /vehicles/v1/**
         url: http://vehiclemanager.backend.svc.cluster.local:8083/vehicles