### STAGE 1: Build ###

FROM node:10.15.0 as builder

# Preparing working environment.
ARG buildEnv=development
RUN mkdir -p /usr/src/monitoringdashboard
WORKDIR /usr/src/monitoringdashboard

# Installing dependencies.
COPY package*.json /usr/src/monitoringdashboard/
RUN npm install
RUN npm install bootstrap
COPY . /usr/src/monitoringdashboard

# Building app.
RUN npm run-script build

### STAGE 2: Setup ###

FROM nginx:1.13.12-alpine

# Removing nginx default page.
RUN rm -rf /usr/share/nginx/html/*

# Copying nginx configuration.
COPY /nginx/nginx.conf /etc/nginx/conf.d/default.conf

COPY --from=builder /usr/src/monitoringdashboard/dist/monitoringdashboard /usr/share/nginx/html

# Exposing ports.
EXPOSE 80

# Starting server.
CMD ["nginx", "-g", "daemon off;"]
