image:
  repository: "vehiclesdashboardregistry.azurecr.io/vehiclesimulator"
  tag: "52"
  pullPolicy: "IfNotPresent"

replicas: 1
cluster:
  namespace: frontend 

resources:
  requests:
    memory: 250Mi
    cpu: 40m
  limits:
    memory: 2Gi
    cpu: 1


env: {}
#  - name: "JAVA_OPTS2"
#    value: "-Dserver.port=8080"

