image:
  repository: "vehiclesdashboardregistry.azurecr.io/vehiclemanager"
  tag: "52"
  pullPolicy: "IfNotPresent"

replicas: 1
cluster:
  namespace: backend 

resources:
  requests:
    memory: 250Mi
    cpu: 40m
  limits:
    memory: 2Gi
    cpu: 1


env: {}
#  - name: "JAVA_OPTS2"
#    value: "-Dserver.port=8080"


service:
  name: vehiclemanager
  type: ClusterIP
  internalPort: 8083
  externalPort:  8083
  ## Service annotations
  ##
  annotations: {}
